services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    NiR\GhDashboard\Ingestion\Http\:
        resource: '../src/Ingestion/Http/*{Action,Responder}.php'
        public: true

    NiR\GhDashboard\Ingestion\Http\SignatureChecker:
        arguments:
            $key: "%secret%"

    NiR\GhDashboard\Ingestion\DataAccess\:
        resource: '../src/Ingestion/DataAccess/*'

    NiR\GhDashboard\Ingestion\DataAccess\DoctrineRawEventPersister:
        arguments:
            $connection: '@doctrine.dbal.default_connection'

    NiR\GhDashboard\Ingestion\UseCases\IngestEvent\UseCase: ~
