services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    NiR\GhDashboard\Contexts\Ingestion\Http\:
        resource: '../../../src/Contexts/Ingestion/Http/*{Action,Responder}.php'
        public: true

    NiR\GhDashboard\Contexts\Ingestion\Http\SignatureChecker:
        arguments:
            $key: "%secret%"

    NiR\GhDashboard\Contexts\Ingestion\DataAccess\:
        resource: '../../../src/Contexts/Ingestion/DataAccess/*'

    NiR\GhDashboard\Contexts\Ingestion\DataAccess\DoctrineRawEventPersister:
        arguments:
            $connection: '@doctrine.dbal.default_connection'

    NiR\GhDashboard\Contexts\Ingestion\UseCases\IngestEvent\UseCase: ~
