framework:
    secret: "%env(SECRET)%"
    profiler: ~

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_sqlite
                path: "%db_path%"

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.project_dir%/var/logs/%kernel.environment%.log"
            level: DEBUG
            formatter: "monolog.formatter.line"
