framework:
    secret: "%env(SECRET)%"
    profiler: ~

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_sqlite
                path: "%db_path%"
