imports:
    - { resource: parameters.yml }
    - { resource: services/contexts/ingestion.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    NiR\GhDashboard\Symfony\ControllerResolver: ~

    controller_resolver:
        alias: NiR\GhDashboard\Symfony\ControllerResolver

    NiR\GhDashboard\Symfony\CreateSchemaCommand: ~

    NiR\GhDashboard\Symfony\HttpMessageConverter: ~

    NiR\GhDashboard\Symfony\SchemaManager:
        arguments:
            $tables:
                - "@NiR\\GhDashboard\\Contexts\\Ingestion\\DataAccess\\DoctrineRawEventTable"

    NiR\GhDashboard\Symfony\ExceptionListener: ~

    Http\Message\MessageFactory\DiactorosMessageFactory: ~
